version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  web:
    build: ./webServ
    volumes:
      - "./sources:/var/www/html"
    ports:
      - 9000:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 9001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306